************* CLIENT *************************************************************************************************************

### create Client
POST http://localhost:8888/client/create
Content-Type: application/json

{
  "id": 8,
  "name": "Sem",
  "lastName": "Qwerty"
}

### delete client by id
DELETE http://localhost:8888/client/1

### find Client by id
GET http://localhost:8888/client/?id=2

********************* PRODUCT **************************************************************************************************

### create product
POST http://localhost:8888/product/create?amount=22
Content-Type: application/json

{
  "id": 77,
  "name": "Iphone8",
  "price": 50000,
  "category": "Smartphone",
  "brand": "Apple",
  "storeId": 1
}

### delete product by id
DELETE http://localhost:8888/product/1

### get product by id
GET http://localhost:8888/product/?id=77

### get products by params
GET http://localhost:8888/product/findProducts?brand=Apple

### buy product
POST http://localhost:8888/product/buy?id=10&clientId=1&productId=4&amount=2

******************* STORE ***************************************************************************************************

### get store by id
GET http://localhost:8888/store/?id=9

### create store
POST http://localhost:8888/store/create
Content-Type: application/json

{
  "id": 9,
  "name": "Amazon"
}

### Analytics
*************************** Analytics **********************************************************

### 1
GET http://localhost:8888/analytics/nameStoreAndAmountCategory

### 2
GET http://localhost:8888/analytics/nameClientAndMoneySpentOnBrand?brand=LG

### 3
GET http://localhost:8888/analytics/storeByMaxSoldBrand?brand=Apple

### 4
GET http://localhost:8888/analytics/nameClientAndNumberOfPurchases/4

### 5
GET http://localhost:8888/analytics/brandAndAmountCategory?priceLimit=5000

### 6
GET http://localhost:8888/analytics/avgPriceByCategory?category=TV

### 7
GET http://localhost:8888/analytics/categoryAndMaxPrice?category=TV

### 8
GET http://localhost:8888/analytics/productMaxPriceBrand

### 9
GET http://localhost:8888/analytics/storeAndAmountProductsOneBrand?brand=Apple

### 10
GET http://localhost:8888/analytics/clientAndAmountMoneyByStore/4

### 11
GET http://localhost:8888/analytics/storeAndSumMoneyByBrand?brand=LG