CREATE TABLE Product (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(100) NOT NULL,
 price BIGINT NOT NULL,
 category VARCHAR(20) NOT NULL,
 brand VARCHAR(30) NOT NULL,
 amount INT
);

CREATE TABLE Store (
   id SERIAL PRIMARY KEY NOT NULL,
   name VARCHAR(100) NOT NULL,
   products VARCHAR(1000)
);

CREATE TABLE Client (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    favorites VARCHAR(1000),
    history VARCHAR(1000)
);