CREATE TABLE Product (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(100) NOT NULL,
 price BIGINT NOT NULL,
 category VARCHAR(50) NOT NULL,
 brand VARCHAR(50) NOT NULL,
 amount INT
);

CREATE TABLE Store (
   id SERIAL PRIMARY KEY NOT NULL,
   name VARCHAR(100) NOT NULL
);

CREATE TABLE Client (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

CREATE TABLE Favorites (
    id SERIAL PRIMARY KEY NOT NULL,
    clientId INTEGER NOT NULL,
    productId INTEGER NOT NULL
);

CREATE TABLE PurchaseHistory (
    id SERIAL PRIMARY KEY NOT NULL,
    clientId INTEGER NOT NULL,
    storeId INTEGER NOT NULL,
    productId INTEGER NOT NULL
);

CREATE TABLE ProductInStock (
    id SERIAL PRIMARY KEY NOT NULL,
    storeId INTEGER NOT NULL,
    productId INTEGER NOT NULL
);